CREATE LOCAL TEMPORARY TABLE PREWORK ON COMMIT PRESERVE ROWS AS 
SELECT * FROM EDW_EXTERNAL_INPUT_DATA.IDM_BR_HIER_SUP_GRP
 WHERE 1<>1;

SELECT * FROM PREWORK;



DROP TABLE PREWORK
 
INSERT INTO PREWORK(
OFC_ID
,UID
,UNIT
,ASSOC_NM
,GRP_TYPE
,GRP_LVL
,GRP_NM
,RGN_NM
,effective_dt
,ROW_PROCESS_DTM
,AUDIT_ID
,SOURCE_SYSTEM_ID
--,ROW_SID
)
SELECT 
OFC_ID
,UID
,UNIT
,ASSOC_NM
,GRP_TYPE
,GRP_LVL
,GRP_NM
,RGN_NM
,effective_dt
,ROW_PROCESS_DTM
,AUDIT_ID
,SOURCE_SYSTEM_ID
--,ROW_SID
FROM(SELECT 
OFC_ID                          AS OFC_ID
,CLEAN_STRING(UID)              AS UID
,CLEAN_STRING(UNIT)             AS UNIT
,CLEAN_STRING(ASSOC_NM)         AS ASSOC_NM
,CLEAN_STRING(GRP_TYPE)         AS GRP_TYPE
,CLEAN_STRING(GRP_LVL)          AS GRP_LVL
,CLEAN_STRING(SUBSTRING(GRP_NM, 1, 50))         AS GRP_NM
,CLEAN_STRING(RGN_NM)           AS RGN_NM
,CURRENT_DATE                   AS effective_dt
,CURRENT_TIMESTAMP              AS ROW_PROCESS_DTM
,-1                             AS AUDIT_ID
,CLEAN_STRING('15')             AS SOURCE_SYSTEM_ID
--,1::INTEGER                      AS ROW_SID
FROM EDW_STAGING.IDM_BR_HIER_SUP_GRP)Q1;


CREATE LOCAL TEMPORARY TABLE WORK1 ON COMMIT PRESERVE ROWS AS 
SELECT * FROM PREWORK;

SELECT * FROM WORK1;

DROP TABLE WORK1;










