CREATE LOCAL TEMPORARY TABLE TEMP ON COMMIT PRESERVE ROWS AS 
SELECT * FROM edw_external_input_data.idm_br_hier_sup_grp WHERE 1<>1;

SELECT * FROM TEMP LIMIT 10;

DROP TABLE TEMP;

INSERT INTO TEMP(
OFC_ID
,UID
,UNIT
,ASSOC_NM
,GRP_TYPE
,GRP_LVL
,GRP_NM
,RGN_NM
,EFFECTIVE_DT
,ROW_PROCESS_DTM
,AUDIT_ID
,SOURCE_SYSTEM_ID
--,ROW_SID
)
SELECT 
OFC_ID
,UID
,UNIT
,ASSOC_NM
,GRP_TYPE
,GRP_LVL
,GRP_NM
,RGN_NM
,EFFECTIVE_DT
,ROW_PROCESS_DTM
,AUDIT_ID
,SOURCE_SYSTEM_ID
FROM(
SELECT 
CLEAN_STRING(OFC_ID)       AS OFC_ID
,CLEAN_STRING(UID)         AS UID
,CLEAN_STRING(UNIT)        AS UNIT
,CLEAN_STRING(ASSOC_NM)    AS ASSOC_NM
,CLEAN_STRING(GRP_TYPE)    AS GRP_TYPE
,CLEAN_STRING(GRP_LVL)     AS GRP_LVL
,CLEAN_STRING(SUBSTRING(GRP_NM,1,50) )   AS GRP_NM
,CLEAN_STRING(RGN_NM)      AS RGN_NM
,REC_STRT_DT               AS EFFECTIVE_DT
,CURRENT_TIMESTAMP         AS ROW_PROCESS_DTM
,1                         AS AUDIT_ID
,SRC_SYS_ID                AS SOURCE_SYSTEM_ID
FROM PROD_PDCR_HIER_VW_TERSUN.HIER_SUP_GRP_VW)Q_1;


--checking duplicates
SELECT GRP_TYPE,OFC_ID,UNIT,UID,ASSOC_NM,GRP_LVL,GRP_NM,RGN_NM,COUNT(*) 
FROM TEMP
GROUP BY GRP_TYPE,OFC_ID,UNIT,UID,ASSOC_NM,GRP_LVL,GRP_NM,RGN_NM
HAVING COUNT(*)>1 ORDER BY COUNT(*);


--checking recent date
SELECT GRP_TYPE,OFC_ID,UNIT,UID,ASSOC_NM,GRP_LVL,GRP_NM,RGN_NM,MAX(EFFECTIVE_DT) 
FROM TEMP GROUP BY GRP_TYPE,OFC_ID,UNIT,UID,ASSOC_NM,GRP_LVL,GRP_NM,RGN_NM HAVING COUNT(*)>1;




SELECT * FROM TEMP WHERE GRP_TYPE='Delegation' AND OFC_ID='001' AND UNIT='1748' AND
UID='08Ex9qxb' AND ASSOC_NM='Nkisahoj' AND GRP_LVL='8'


CREATE LOCAL TEMPORARY TABLE TEMP1 ON COMMIT PRESERVE ROWS AS 
SELECT * FROM TEMP WHERE 1<>1;


SELECT * FROM TEMP1;

DROP TABLE TEMP1;


--inserted only the most recent record from duplicates
INSERT INTO TEMP1(
OFC_ID
,UID
,UNIT
,ASSOC_NM
,GRP_TYPE
,GRP_LVL
,GRP_NM
,RGN_NM
,EFFECTIVE_DT
,ROW_PROCESS_DTM
,AUDIT_ID
,SOURCE_SYSTEM_ID
)
SELECT 
OFC_ID
,UID
,UNIT
,ASSOC_NM
,GRP_TYPE
,GRP_LVL
,GRP_NM
,RGN_NM
,EFFECTIVE_DT
,ROW_PROCESS_DTM
,AUDIT_ID
,SOURCE_SYSTEM_ID
FROM(
SELECT
CLEAN_STRING(OFC_ID)       AS OFC_ID
,CLEAN_STRING(UID)         AS UID
,CLEAN_STRING(UNIT)        AS UNIT
,CLEAN_STRING(ASSOC_NM)    AS ASSOC_NM
,CLEAN_STRING(GRP_TYPE)    AS GRP_TYPE
,CLEAN_STRING(GRP_LVL)     AS GRP_LVL
,CLEAN_STRING(SUBSTRING(GRP_NM,1,50) )   AS GRP_NM
,CLEAN_STRING(RGN_NM)      AS RGN_NM
,MAX(EFFECTIVE_DT)         AS EFFECTIVE_DT
,CURRENT_TIMESTAMP         AS ROW_PROCESS_DTM
,1                         AS AUDIT_ID
,SOURCE_SYSTEM_ID          AS SOURCE_SYSTEM_ID
FROM TEMP
GROUP BY
GRP_TYPE,OFC_ID,UNIT,UID,ASSOC_NM,GRP_LVL,GRP_NM,RGN_NM,SOURCE_SYSTEM_ID
)Q_2;
